### ISSUE TITLE
Intro disappeared after installed

### ISSUE THREAD

**Issue by redbug312** [kyazdani42/nvim-tree.lua#193]
The minimal config installed with packer:

```lua
vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function()
    use {'wbthomason/packer.nvim', opt = true}
    use 'kyazdani42/nvim-tree.lua'
end)
```

And the expected intro screen will disappear after installed.
![intro](https://user-images.githubusercontent.com/11537681/107015678-fb7f8500-67d7-11eb-9dd6-c62fb1cd8f9f.png)

It seems highlight commands in [`colors.setup()`][code] triggers redraw and cleans the intro screen.
Can that part be separated into a `syntax/` folder?

[code]: https://github.com/kyazdani42/nvim-tree.lua/blob/b2852578769b53430af678ae7a99482f2a4be0da/lua/lib/colors.lua#L75

**Comment by kyazdani42** [comment]
i try to avoid running vimscript, so maybe this issue should be addressed in another way. Maybe loading the syntax through a lua call in the syntax folder would help. Not sure about that, i'm really busy atm so if you feel like doing this go for it :)

**Comment by osa1** [comment]
Came here to report this. The intro shows for maybe half a second, then disappears.

**Comment by kyazdani42** [comment]
closed in #202

**Comment by gegoune** [comment]
This is still an issue, not sure whether root cause is the same, but with nvim-tree installed intro screen shows very briefly at start and then disappears.

**Comment by kyazdani42** [comment]
not sure when it came back, but i sure should take a look

**Comment by kyazdani42** [comment]
i think this is not related to nvim-tree because when disabled, the intro still is erased. Might be caused by another plugin.

**Comment by z0xyz** [comment]
The exact same problem is still persistent !
@kyazdani42 I guess The bug should be reopened in order to address this issue

**Comment by kyazdani42** [comment]
It is not with my config, as i said before, it must be caused by another plugin.

**Comment by z0xyz** [comment]
I've already narrowed down the factors that might potentially cause that by disabling all of the additional plugins that i have, left nvim-tree the only one remaining. Yet the problem still persist .

**Comment by kyazdani42** [comment]
can you provide at least the minimal configuration with nvim-tree where it happens ? I cannot reproduce this.

**Comment by z0xyz** [comment]
All i have is the exact default [configuration](https://www.lifewire.com/best-free-sports-streaming-sites-4169519) without any modifications .

**Comment by tobiassen** [comment]
I'm having the same problem, disabling nvim-tree and the intro shows up as normal, enabling nvim-tree again and the intro flash and disappear.  
How can I help troubleshoot this?

**Comment by kyazdani42** [comment]
I've reproduced, and managed to track it down to buffer creation. I'm not sure why this happens again, but i might be able to fix it once i rewrite the view/setup.

**Comment by kyazdani42** [comment]
will be ok, i'll probably be able to rewrite the whole setup this weekend.
The thing is if i create a new buffer after vim has initialized, it clears the screen :smile:.

**Comment by z0xyz** [comment]
I'm really sorry for the previous incorrect URL .
