### ISSUE TITLE
Suggestion: folders open and close different colors

### ISSUE THREAD

**Issue by hrqmonteiro** [kyazdani42/nvim-tree.lua#229]
Hi, it would be nice to have different colors for the opened folders and the default folder glyphs, like we could do in Nerdtree, like this:

![2021-03-12_18-17](https://user-images.githubusercontent.com/17055027/110999481-3046a500-835f-11eb-9980-1d9db1bed26b.png)

A different highlight group for the opened ones and for the closed ones.

**Comment by kyazdani42** [comment]
you could implement this if you wish, you've got to modify the color table (to add another group), and the highlight choice in renderer.lua :)

**Comment by hrqmonteiro** [comment]
I'm not a lua programmer, i tried to do it but i couldn't... Even forked the repo, so if i could manage to do it i would PR. But i am not able to.

Thanks to the attention anyway.

**Comment by kyazdani42** [comment]
Hi, do not close suggestions that might be realized by other people :) maybe i'll have time at some point

**Comment by hrqmonteiro** [comment]
Oh sorry, didn't realized that, my mistake

**Comment by vuki656** [comment]
Hey @hrqmonteiro you could do something like this 

Lua variant
```
vim.g.nvim_tree_icons = {
    folder = {
        default = "",
        open = "",
        empty_open = "",
        empty = "",
        symlink = "",
    }
}
```


Viml variant
```
let g:nvim_tree_icons = {
    \ 'folder': {
    \   'default': "",
    \   'open': "",
    \   'empty_open': "",
    \   'empty': "",
    \   'symlink': "",
    \   }
    \ }
```

It will do this
![image](https://user-images.githubusercontent.com/8104698/112717276-e4ae0280-8eeb-11eb-97c3-ccda24ce4135.png)

Is this what you had in mind?

**Comment by hrqmonteiro** [comment]
> Hey @hrqmonteiro you could do something like this
> 
> Lua variant
> 
> ```
> vim.g.nvim_tree_icons = {
>     folder = {
>         default = "",
>         open = "",
>         empty_open = "",
>         empty = "",
>         symlink = "",
>     }
> }
> ```
> 
> Viml variant
> 
> ```
> let g:nvim_tree_icons = {
>     \ 'folder': {
>     \   'default': "",
>     \   'open': "",
>     \   'empty_open': "",
>     \   'empty': "",
>     \   'symlink': "",
>     \   }
>     \ }
> ```
> 
> It will do this
> ![image](https://user-images.githubusercontent.com/8104698/112717276-e4ae0280-8eeb-11eb-97c3-ccda24ce4135.png)
> 
> Is this what you had in mind?

Actually no, this i already have (a different icon for the closed and the open), i wanted to highlight it differently, a color for each of them, see?

**Comment by afonsocarlos** [comment]
I can take this too. I was thinking about highlighting currently opened files that are pretty similar to what @hrqmonteiro is looking for, maybe I can do both.

**Comment by kyazdani42** [comment]
has been fixed in #258

**Comment by hrqmonteiro** [comment]
> has been fixed in #258

Okay, i was using the fork of afonsocarlos, for like a week, and i was having the folder icon changed it's color when i opened it.

Today i say what you merged, and i switched to the main repo and main branch. But just the name of the opened folder is changing color.

Why did you chose to go this way? Can't we have the folder ICON change the color?

**Comment by afonsocarlos** [comment]
@kyazdani42 I checked here and i think it could be the case of only condition this part:

https://github.com/kyazdani42/nvim-tree.lua/blob/090697e71fe614cc13f218fc751a651cf4fada4f/lua/nvim-tree/renderer.lua#L45-L48

To something like this:

```lua
  hl_icon = 'NvimTreeFolderIcon'
  if vim.g.nvim_tree_highlight_opened_files then hl_icon = 'NvimTreeOpenedFolderIcon' end
  table.insert(hl, {hl_icon, line, depth, depth+icon_len})
```
What do you think?

**Comment by kyazdani42** [comment]
yep go for it

**Comment by hrqmonteiro** [comment]
Still doesn't work.

I literally use the afonso fork on this [commit](https://github.com/afonsocarlos/nvim-tree.lua/commits/feat/add-highlight) because it has the option to highlight the icon instead of the text.

**Comment by afonsocarlos** [comment]
@hrqmonteiro we're working on that already, there's a PR in progress to improve the level of customization for opened files highlighting

**Comment by hrqmonteiro** [comment]
Will this be actually implemented (again) someday? Just asking.

I updated the plugin to the latest version just to check, and still only the name of the opened folder can be highlighted. Couldn't we just implement what was implemented in this [commit](https://github.com/afonsocarlos/nvim-tree.lua/commits/feat/add-highlight) to have the icons colored? I am using this commit and it looks so damn nice with the opened icon different color.

**Comment by kyazdani42** [comment]
i could check out the code, i don't use the feature myself but i could make it more configurable

**Comment by afonsocarlos** [comment]
@hrqmonteiro I think you can get something pretty similar to the commit you mentioned by adding this to your `.vimrc/init.vim`

```vim
    let g:nvim_tree_highlight_opened_files = 1

    highlight def link NvimTreeOpenedFolderName NvimTreeOpenedFile
```

**Comment by hrqmonteiro** [comment]
> @hrqmonteiro I think you can get something pretty similar to the commit you mentioned by adding this to your `.vimrc/init.vim`
> 
> ```viml
>     let g:nvim_tree_highlight_opened_files = 1
> 
>     highlight def link NvimTreeOpenedFolderName NvimTreeOpenedFile
> ```

This doesn't do anything close to what it was. The best thing was when you could highlight only the folder color, not together with the folder name, and ONLY the opened folder icon, not together with the opened folder name. This is just sad..

I will keep using that very old commit, cause that was actually good.

**Comment by kyazdani42** [comment]
this folder close/open thing must be rewritten to accept more user behaviors, it's not configurable enough as it is :)
