### ISSUE TITLE
shows dobule of all files and directories under git project

### ISSUE THREAD

**Issue by shaeinst** [kyazdani42/nvim-tree.lua#519]
https://user-images.githubusercontent.com/41078534/126079282-0bf227e8-fdd9-4b11-af01-77f8b72cdfd9.mp4

**Comment by kyazdani42** [comment]
Hi !
I cannot reproduce this, can you provide:
1) you neovim version
2) your nvim-tree version
3) a minimal sample config file from which i can reproduce this

**Comment by shaeinst** [comment]
humm interesting... it's gone. i don't know how but problem has solved by itself. i will reopen this thread if i got into it again.

**Comment by shaeinst** [comment]
sorry My Apology. i'm still getting this duplicates

os: 5.12.15-arch1-1
```

neovim --version
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.0/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```
i don't know how to check plugin version but i install it using Packer i.e use { 'kyazdani42/nvim-tree.lua' }
> your nvim-tree version


i disabled all plugins and configs and retried under git again, it's still showing duplicates. means i tried with zero config

**Comment by vinicius507** [comment]
The same is happening to me.

OS: Linux myriad 5.13.4-arch1-1 #1 SMP PREEMPT Tue, 20 Jul 2021 16:58:51 +0000 x86_64 GNU/Linux
Neovim:
```
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.0/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

The plugin is at master(just ran `:PackerUpdate` and it still happens).

**Comment by vinicius507** [comment]
My plugin configuration:

```lua
local vimg = vim.g

local config = {
	side = 'left',
	width = 30,
	ignore = { '.git', 'node_modules', '.cache' },
	gitignore = 1,
	auto_open = 0,
	auto_close = 0,
	auto_ignore_ft = {},
	quit_on_open = 1,
	follow = 1,
	indent_markers = 0,
	hide_dotfiles = 0,
	git_hl = 0,
	root_folder_modifier = ':t',
	tab_open = 0,
	width_allow_resize = 0,
	disable_netrw = 1,
	hijack_netrw = 1,
	add_trailing = 0,
	group_empty = 1,
	lsp_diagnostics = 1,
	special_files = { 'README.md', 'Makefile' },
	show_icons = { git = 0, folders = 1, files = 1 },
	icons = {
		default = '',
		symlink = '',
		git = {
			unstaged = '✗',
			staged = '✓',
			unmerged = '',
			renamed = '➜',
			untracked = '★',
			deleted = '',
			ignored = '◌',
		},
		folder = {
			default = '',
			open = '',
			empty = '',
			empty_open = '',
			symlink = '',
			symlink_open = '',
		},
		lsp = {
			hint = '',
			info = '',
			warning = '',
			error = '',
		},
	},
}

local set_options = function(cfg)
	for key, value in pairs(cfg) do
		vimg['nvim_tree_' .. key] = value
	end
end

set_options(config)
```

**Comment by gegoune** [comment]
I have noticed that I will get duplicated entries when I start `nvim` and open nvim-tree without any buffer read, if I first load some file tree does not have duplicates. Can someone confirm this, please?

**Comment by vinicius507** [comment]
> I have noticed that I will get duplicated entries when I start `nvim` and open nvim-tree without any buffer read, if I first load some file tree does not have duplicates. Can someone confirm this, please?

The opposite is happening with me. If I just run `nvim` and open nvim-tree, it won't have duplicates. If I open nvim loading a file tree(e.g. `nvim main.c`) they appear.

**Comment by Iron-E** [comment]
> I have noticed that I will get duplicated entries when I start `nvim` and open nvim-tree without any buffer read, if I first load some file tree does not have duplicates. Can someone confirm this, please?

I get the same thing, but even when reading a buffer. For me it is:

1. Open `nvim`, with `g:nvim_tree_auto_open == 0`.
2. `<Cmd>NvimTreeToggle<CR>`

Whether or not a buffer is loaded has no effect for me.

**Comment by kyazdani42** [comment]
should be fixed now, reopen if it's happening again
